### ISSUE TITLE
Fix typo in agents/minimax_agent.py

### ISSUE THREAD

**Issue by levzlotnik** [nabaco/4-in-row#11]
Rename `AlphaBetaPruningAget` to `AlphaBetaPruningAgent` (typo).

**Comment by nabaco** [comment]
Changed the issue to do creation of separate issues for each task for better project management

**Comment by levzlotnik** [comment]
No need for such grained separation, the typo renaming is literally a single keystroke

**Comment by levzlotnik** [comment]
Done.
