### ISSUE TITLE
Implement and investigate heuristics for search agents

### ISSUE THREAD

**Issue by nabaco** [nabaco/4-in-row#21]
# Implement three heuristics:
- Aggressive (Player win < opponent loss)
- Passive (Player win > opponent loss)
- Neutral (Player win == opponent loss)

# Investigate results:
- Write a script that will do run the different agents against each other, using different heuristics and record results
- Investigate the results to see which agent and which heuristic is the best

**Comment by nabaco** [comment]
**Specifications:**

1. **Must**
    1. Keep a table of matchups and the result of the match between any 2 agents from the tournament.
    2. At the end of the script - print the result table.

2. **Should**
    1. Generate the set of agents at the beginning and use them to create matches. Use a single loop over all the pairs of agents and the body of the loop will just run a single match of this pair. The result of the match is then saved into the table.
    2. Agents names that describe them nicely, not "agent1,agent2" etc, but "agent_minimax_depth3_aggressive, agent_alphabeta_depth5_neutral"
 
3. **Could**
    1. Use different timeout configurations, of course a random agent doesn't need a timeout config because we assume that it takes 0 time to output an action, but the search agents are always bound by time. Hence you could also try making good search agents lose by timing them out.
    2.  print out a scoreboard for each type of match, e.g.:
         "Match 'No Timeout' - scoreboard - 
             1) alphabeta_depth6_neutral
             2) alphabeta_depth6_aggressive
             3) ...
         "

4. **Won't**
    1. Have any copy pasted code within it. Do it as pythonic as humanly possible.

**Comment by levzlotnik** [comment]
Great template! I love it!  
I corrected the formulation - aggressive behavior would be defined as "wanting to crush the opponent", i.e. making him lose as much as possible without regard to your own safety.
Passive is vise versa - you don't care about the opponent, only about your own points.
Neutral is taking both into account, which is the middle ground.
